# Generated by Django 2.2.3 on 2019-07-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('publisher', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('completed', models.BooleanField(default=False)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Console')),
            ],
        ),
    ]
